## Copyright © 2020, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

title: "Create Apache Tomcat on Arm-based Ampere A1 compute connected to an autonomous database in Oracle Cloud Infrastructure,"
stackDescription: "Deploy Apache Tomcat on Arm-based Ampere A1 compute connected to an autonomous database in Oracle Cloud Infrastructure."
schemaVersion: 1.1.0
version: "20190404"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid
  - region
  - release
  - oracle_instant_client_version
  - oracle_instant_client_version_short

- title: Required Configuration
  visible: true  
  variables:
  - compartment_ocid
  - availablity_domain_name
  - atp_password
  - atp_private_endpoint
  - atp_free_tier
  - numberOfNodes
  - tomcat_version
  - show_advanced

- title: Load Balancer Configuration
  visible: 
      and:
        - show_advanced
  variables:
  - lb_shape 
  - flex_lb_min_shape
  - flex_lb_max_shape 

- title: Compute Instances Configuration
  visible: 
      and:
        - show_advanced
  variables:
  - ssh_public_key
  - InstanceShape
  - InstanceFlexShapeOCPUS
  - InstanceFlexShapeMemory
  - instance_os
  - linux_os_version

- title: Networking Optional Configuration
  visible: 
      and:
        - show_advanced
  variables:
  - igw_display_name
  - vcn01_cidr_block
  - vcn01_dns_label
  - vcn01_display_name
  - vcn01_subnet_pub01_cidr_block
  - vcn01_subnet_pub01_display_name
  - vcn01_subnet_pub02_cidr_block
  - vcn01_subnet_pub02_display_name  
  - vcn01_subnet_app01_cidr_block
  - vcn01_subnet_app01_display_name 
  - vcn01_subnet_db01_cidr_block
  - vcn01_subnet_db01_display_name

- title: ATP Optional Configuration
  visible: 
      and:
        - show_advanced
  variables:
  - atp_cpu_core_count
  - atp_data_storage_size_in_tbs
  - atp_db_name
  - atp_db_version
  - atp_defined_tags_value
  - atp_name
  - atp_username
  - atp_freeform_tags
  - atp_license_model
  - atp_tde_wallet_zip_file
  - atp_private_endpoint_label

variables:

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false
  
  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    visibile: true
    title: Compartment
    description: "Compartment where you want to create the solution resources"

  availablity_domain_name:
    type: oci:identity:availabilitydomain:name
    required: true
    visibile: true
    title: "Availability Domain to be chosen"
    description: "Availability Domain to be chosen"
    dependsOn:
      compartmentId: ${compartment_ocid}
      
  region:
    type: oci:identity:region:name
    required: true
    visibile: true
    title: Region
    description: "Region where you want to deploy the resources defined by this stack."

  atp_password:
    type: password
    required: true
    visibile: true
    title: "ATP Database Password for ADMIN user."
    description: "ATP Database Password for ADMIN user."
    minLength: 12
    maxLength: 30
    pattern: ^[A-Za-z][A-Za-z0-9_#\$]+$ 

  numberOfNodes:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 2
    title: "How many Tomcat Nodes?"
    description: "Choose number of Tomcat Nodes to be deployed."

  tomcat_version:
    type: enum
    title: "Tomcat Version"
    description: "Choose Tomcat Version"
    default: "9.0.45"
    required: false 
    enum:
      - "9.0.45"
      - "8.5.65"
      - "7.0.108"
 
  # Optional Configuration  
  
  ssh_public_key:
    type: oci:core:ssh:publickey
    title: "Public SSH Key"
    description: "Choose public SSH Key to be uploaded into compute instances."
    required: false

  lb_shape:
    type: enum
    title: "LoadBalancer Shape"
    description: "Choose LoadBalancer Shape"
    default: "flexible"
    required: false 
    enum:
      - "flexible"
      - "100Mbps"
      - "10Mbps"
      - "10Mbps-Micro"
      - "400Mbps"
      - "8000Mbps"

  flex_lb_min_shape:
    type: enum
    required: false
    default: "10"
    title: "LB Flex Min Shape"
    description: "Choose Minimum Shape for Flex Load Balancer."
    enum:
      - "10"
      - "100"
      - "1000"
      - "400"
      - "8000"
    visible:
      and:
        - eq:
          - lb_shape 
          - "flexible"

  flex_lb_max_shape:
    type: enum
    required: false
    default: "100"
    title: "LB Flex Max Shape"
    description: "Choose Maximum Shape for Flex Load Balancer."
    enum:
      - "10"
      - "100"
      - "1000"
      - "400"
      - "8000"
    visible:
      and:
        - eq:
          - lb_shape 
          - "flexible"

  igw_display_name:
    type: string
    required: false
    title: "InternetGateway Display Name"
    description: "Type InternetGateway Display Name."
    default: "internet-gateway"

  vcn01_cidr_block:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR Block"
    description: "Choose CIDR block for your VCN."
    default: "10.0.0.0/16"

  vcn01_dns_label:
    type: string
    required: false
    title: "VCN DNS Label"
    description: "Choose DNS Label for your VCN."
    default: "vcn01"

  vcn01_display_name:
    type: string
    required: false
    title: "VCN Display Name"
    description: "Choose Display Name for your VCN."
    default: "vcn01"

  vcn01_subnet_pub01_cidr_block:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Load Balancer Public Subnet CIDR Block"
    description: "Choose CIDR block for your Load Balancer Public Subnet."
    default: "10.0.1.0/24"

  vcn01_subnet_pub01_display_name:
    type: string
    required: false
    title: "Load Balancer Public Subnet Display Name"
    description: "Choose Display Name for your Load Balancer Public Subnet."
    default: "vcn01_subnet_pub01"

  vcn01_subnet_pub02_cidr_block:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Bastion Host Public Subnet CIDR Block"
    description: "Choose CIDR block for your Bastion Host Public Subnet."
    default: "10.0.2.0/24"

  vcn01_subnet_pub02_display_name:
    type: string
    required: false
    title: "Bastion Host Public Subnet Display Name"
    description: "Choose Display Name for your Bastion Host Public Subnet."
    default: "vcn01_subnet_pub02"

  vcn01_subnet_app01_cidr_block:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Tomcat Servers Public Subnet CIDR Block"
    description: "Choose CIDR block for your Tomcat Servers Public Subnet."
    default: "10.0.10.0/24"

  vcn01_subnet_app01_display_name:
    type: string
    required: false
    title: "Tomcat Servers Public Subnet Display Name"
    description: "Choose Display Name for your Tomcat Servers Public Subnet."
    default: "vcn01_subnet_app01"

  vcn01_subnet_db01_cidr_block:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "ATP Private Subnet CIDR Block"
    description: "Choose CIDR block for your ATP Private Subnet."
    default: "10.0.20.0/24"
    visible: atp_private_endpoint

  vcn01_subnet_db01_display_name:
    type: string
    required: false
    title: "ATP Private Subnet Display Name"
    description: "Choose Display Name for your ATP Private Subnet."
    default: "vcn01_subnet_db01"
    visible: atp_private_endpoint

  InstanceShape:
    type: oci:core:instanceshape:name
    required: false
    title: "Instance Shape"
    description: "A shape is a template that determines the number of CPUs, amount of memory, and other resources allocated to a newly created instance."
    default: "VM.Standard.A1.Flex"
    dependsOn:
      compartmentId: ${compartment_ocid}

  InstanceFlexShapeOCPUS:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
          - eq:
            - InstanceShape 
            - "VM.Standard.E3.Flex"
          - eq:
            - InstanceShape 
            - "VM.Standard.E4.Flex"
          - eq:
            - InstanceShape 
            - "VM.Standard.A1.Flex"
          - eq:
            - InstanceShape 
            - "VM.Optimized3.Flex"

  InstanceFlexShapeMemory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 10
    title: "Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - or:
          - eq:
            - InstanceShape 
            - "VM.Standard.E3.Flex"
          - eq:
            - InstanceShape 
            - "VM.Standard.E4.Flex"
          - eq:
            - InstanceShape 
            - "VM.Standard.A1.Flex"
          - eq:
            - InstanceShape 
            - "VM.Optimized3.Flex"
  
  instance_os:
    type: enum
    required: false
    title: "Instance OS"
    description: "An Operating System that determines the operating system for the instance."
    default: "Oracle Linux"
    enum:
      - "Oracle Linux"

  linux_os_version:
    type: enum
    required: false
    title: "Instance OS version"
    description: "An Operating System version that determines the operating system version for the instance."
    default: "8"
    enum:
      - "8"
      - "7.9"

  atp_private_endpoint:
    type: boolean
    visibile: true
    default: false
    required: true
    title: "ATP Database Private Endpoint"
    description: "Check the box to deploy ATP Database with Private Endpoint."

  atp_free_tier:
    type: boolean
    visibile: true
    default: true
    required: false
    title: "ATP Database Free Tier"
    description: "Check the box to deploy ATP Database Free Tier."

  atp_cpu_core_count:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "ATP Database CPU Core Count"
    description: "Choose how many CPU cores will be used for ATP Instance."

  atp_data_storage_size_in_tbs:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "ATP Database Data Storage Size"
    description: "Choose ATP Database Data Storage Size in terabytes."

  atp_db_name:
    type: string
    required: false
    title: "ATP Database DB Name"
    description: "Choose ATP Database name."

  atp_db_version:
    type: enum
    required: false
    default: "19c"
    title: "ATP Database Version"
    description: "Choose ATP Database version."
    enum:
      - "19c"

  atp_name:
    type: string
    required: false
    title: "ATP Database Display Name"
    description: "Choose ATP Database display name."

  atp_username:
    type: string
    required: false
    title: "ATP Database App Username"
    description: "Choose ATP Database application's username."

  atp_license_model:
    type: enum
    required: false
    default: "LICENSE_INCLUDED"
    title: "ATP Database License Model"
    description: "Choose ATP Database license model."
    enum:
      - "LICENSE_INCLUDED"
      - "BRING_YOUR_OWN_LICENSE"

  atp_tde_wallet_zip_file:
    type: string
    required: false
    visible: false
    default: "tde_wallet_ATPdb1.zip"
    description: "ATP Database TDE Wallet ZIP File"
      
  atp_private_endpoint_label:
    type: string
    required: false
    visible: 
      and:
        - ATP_private_endpoint
    default: "ATPPrivateEndpoint"
    title: "ATP Database Private Endpoint Label"
    description: "Choose ATP Database Private Endpoint label."

  atp_freeform_tags:
    type: string
    required: false
    title: "ATP Database Freeform Tags"
    description: "Choose ATP Database Freeform Tags."

  atp_defined_tags_value:
    type: string
    required: false
    title: "ATP Database Defined Tags"
    description: "Choose ATP Database Defined Tags."

outputs:

  todoapp_url:
    title: "TODO App URL"
    displayText: "TODO App URL"
    type: copyableString
    visible: true

  bastion_public_ip:
    title: "Bastion Host Public IP"
    displayText: "Bastion Host Public IP"
    type: string
    visible: true

